version: '3.8'

services:
  backend:
    build: ./backend
    container_name: furor_backend
    restart: always
    ports:
      - "4017:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - furor_net

  frontend:
    build: ./frontend
    container_name: furor_frontend
    restart: always
    ports:
      - "4018:80"
    networks:
      - furor_net

networks:
  furor_net:
    driver: bridge
