name: Deploy Furor App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Resolve IPv4 address
        id: resolve
        run: |
          IP=$(dig +short A ${{ secrets.SSH_HOST }} | tail -n1)
          echo "IP=$IP" >> $GITHUB_ENV

      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/home/${{ secrets.SSH_USER }}/Docker/furor-app"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/Docker/furor-app
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            docker compose down || true
            docker compose up -d --build
